### ISSUE TITLE
Api question

### ISSUE THREAD

**Issue by noneback** [MarginNote/Addon#2]
```c
- (void)appendHtmlComment:(NSString*)html text:(NSString*)text tag:(NSString*)tag);
```

Wondering how to use the html param.
 Any example to explain the format of param `html`?

**Comment by BryanHuang66** [comment]
This API has some problem and I report it to developers(should be fixed in next version). And get response:
appendHtmlComment(html: string, text: string, size:CGSize, tag: string)
Here is one example to use it :
appendHtmlComment(final_out_put,final_out_put,{width:320, height:320},'MarkDownEditor')

**Comment by noneback** [comment]
I don't consider those api and those docs friendly to us developers. I give up my passion on mn plugin.I will close this issue.Good luck.
